### ISSUE TITLE
Metadata: shared text

### ISSUE THREAD

**Issue by lindsayplatt** [jread-usgs/hyperscales-data-release#13]
Update shared text file

- [x] authors
- [x] pubdate
- [x] doi
- [x] contacts (incl metadata contact)
- [x] accuracy test
- [x] funding creds
- [x] process description 
- [x] distribution person
- [x] liability statement

**Comment by lindsayplatt** [comment]
@jread-usgs please confirm a few things: 

1. Funding credits (seems to be missing part of the USGS office name)

```
This study was funded by the Department of the Interior Northeast Climate Adaptation
Science Center, the United States Geological Survey National Climate

This research used resources of the Core Science Analytics and Synthesis 
Advanced Research Computing program at the U.S. Geological Survey.
```

2. Process description. Currently, the text says GLM v3 is used, but I thought we switched these ones to GLM v2 and kept the TOHA as GLM v3. I can't seem to keep that part straight :)
3. DOI number is listed as http://dx.doi.org/10.5066/P9CA6XP8. Is that right?

**Comment by jordansread** [comment]
Should be

> This study was funded by the Department of the Interior Northeast and North Central Climate Adaptation Science Centers

Yes, this was GLM2, but the most appropriate paper to cite is the one that describes GLM V3, but we make it clear we used the version 2 of the code. 

That DOI looks right
